# Generated by Django 5.1.1 on 2024-09-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catfood',
            old_name='expDate',
            new_name='exp_date',
        ),
        migrations.AddField(
            model_name='catfood',
            name='flavour',
            field=models.CharField(default='original', max_length=10),
        ),
        migrations.AddField(
            model_name='catfood',
            name='product_image',
            field=models.ImageField(default='path/to/default_image.png', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='catfood',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
