# Generated by Django 5.1.1 on 2024-09-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_expdate_catfood_exp_date_catfood_flavour_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatFood',
            new_name='Product',
        ),
    ]
